### ISSUE TITLE
Installation guide needed

### ISSUE THREAD

**Issue by RollingHog** [cyntachs/LiskelOS#1]
Well-well dear sir. First, let me thank you for the tiniest OS for OpenComputers I've ever seen, sometimes I just need it so badly, u'know. But second, It would be very nice to see a better readme. Like, I just wanna install OS and run it, but... I don't know how to do it at all! An OpenOS-like installer or, at least, link to instruction would be incredibly useful.

**Comment by cyntachs** [comment]
Sorry for overlooking something like that. Never really expected anyone to stumble upon this repo. Anyways, the ReadMe has been updated to include a basic installation guide.
