### ISSUE TITLE
Essential minified libraries for OS

### ISSUE THREAD

**Issue by RollingHog** [cyntachs/LiskelOS#2]
Heya, it's me again. Thanks for the new readme, now OS works properly (before I tried to use default OpenOS init.lua, and bad strange things happened). I intend that is's one of the lightest OSes for OpenComputers I've ever seen. I'm damn happy I found it.

The offer: I modified (for compatability with your OS) and minfied two most used libs: event.lua and internet.lua. Their summary size is around 2.5kB. Maybe you could add them to repo?

Link here: https://github.com/RollingHog/Morgana-banking/tree/main/lib

**Comment by RollingHog** [comment]
Usage of [minifier ](https://mothereff.in/lua-minifier) mentioned there gives you about1.6k additional space btw :3

**Comment by cyntachs** [comment]
They are now added as optional libs for LiskelOS

**Comment by RollingHog** [comment]
Many thanks
